mqtt:
  host: 192.168.9.21

database:
  path: /config/frigate.db

ffmpeg:
  global_args: -hide_banner -loglevel error

  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer+genpts+discardcorrupt
    - -flags
    - low_delay
    - -strict
    - experimental
    - -analyzeduration
    - 1000M
    - -probesize
    - 1000M
    - -rw_timeout
    - "5000000"

  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy

rtmp:
  enabled: False

objects:
  track:
    - person
    - car

detect:
  enabled: True
  max_disappeared: 25

record:
  enabled: True
  retain_days: 1
  events:
    max_seconds: 600
    pre_capture: 15
    post_capture: 15

    retain:
      default: 20

cameras:
  
  frontdoor:
    ffmpeg:
      inputs:
        - path: http://192.168.9.51/flv?port1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAM_UN}&password={FRIGATE_CAM_PW}
          roles:
            - record
        - path: http://192.168.9.51/flv?port1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_UN}&password={FRIGATE_CAM_PW}
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 7
    motion:
      mask:
        - 410,444,410,470,221,470,221,444
